// lib/models/quran_mistake_model.dart

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'user_model.dart'; // for TimestampConverter

part 'quran_mistake_model.freezed.dart';
part 'quran_mistake_model.g.dart';

// ─────────────────────────────────────────────────────────────────────────────
// MISTAKE TYPE ENUM
// ─────────────────────────────────────────────────────────────────────────────

enum MistakeType {
  @JsonValue('tajweed') tajweed,
  @JsonValue('pronunciation') pronunciation,
  @JsonValue('reading') reading,
  @JsonValue('skip') skip,
  @JsonValue('addition') addition,
  @JsonValue('other') other,
}

// ─────────────────────────────────────────────────────────────────────────────
// QURAN MISTAKE MODEL
// IMPORTANT: Keep the class body minimal — only factory constructors.
// All instance methods/getters live in QuranMistakeHelpers extension below,
// because freezed cannot generate implementations for class-body methods.
// ─────────────────────────────────────────────────────────────────────────────

@freezed
class QuranMistake with _$QuranMistake {
  // Required private constructor so named factory constructors work.
  const QuranMistake._();

  const factory QuranMistake({
    required String id,
    required int pageNumber,
    required int surahNumber,
    required int ayahNumber,

    // Position on page (relative coordinates 0.0 to 1.0)
    required double xPosition,
    required double yPosition,

    // Mistake details
    required MistakeType type,
    String? wordText,        // The specific word with mistake
    String? correctionNote, // Teacher's correction note

    // Metadata
    @TimestampConverter() DateTime? markedAt,
  }) = _QuranMistake;

  // ── Standard JSON factory (generated by json_serializable) ─────────────────
  factory QuranMistake.fromJson(Map<String, dynamic> json) =>
      _$QuranMistakeFromJson(json);

  // ── Firestore map factory (handles Timestamp ↔ DateTime) ───────────────────
  factory QuranMistake.fromMap(Map<String, dynamic> map) {
    return QuranMistake(
      id: map['id'] as String? ?? '',
      pageNumber: (map['pageNumber'] as num?)?.toInt() ?? 1,
      surahNumber: (map['surahNumber'] as num?)?.toInt() ?? 1,
      ayahNumber: (map['ayahNumber'] as num?)?.toInt() ?? 1,
      type: MistakeType.values.firstWhere(
        (t) => t.name == (map['type'] as String? ?? 'other'),
        orElse: () => MistakeType.other,
      ),
      xPosition: (map['xPosition'] as num?)?.toDouble() ?? 0.0,
      yPosition: (map['yPosition'] as num?)?.toDouble() ?? 0.0,
      wordText: map['wordText'] as String?,
      correctionNote: map['correctionNote'] as String?,
      markedAt: map['markedAt'] != null
          ? (map['markedAt'] is Timestamp
              ? (map['markedAt'] as Timestamp).toDate()
              : DateTime.tryParse(map['markedAt'].toString()))
          : null,
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// INSTANCE HELPERS  — in an extension, NOT in the class body.
// Freezed does not generate implementations for class-body methods,
// but extensions on the generated class work perfectly.
// ─────────────────────────────────────────────────────────────────────────────

extension QuranMistakeHelpers on QuranMistake {
  /// True when the teacher has written a correction note.
  bool get hasComment =>
      correctionNote != null && correctionNote!.isNotEmpty;

  /// Display string for mistake location, including word text when available.
  String get locationText {
    if (wordText != null && wordText!.isNotEmpty) {
      return 'صفحة $pageNumber - آية $ayahNumber: $wordText';
    }
    return 'صفحة $pageNumber - آية $ayahNumber';
  }

  /// Human-readable time-ago string (Arabic).
  String get timeAgo {
    if (markedAt == null) return 'غير محدد';
    final diff = DateTime.now().difference(markedAt!);
    if (diff.inDays > 0) return 'منذ ${diff.inDays} يوم';
    if (diff.inHours > 0) return 'منذ ${diff.inHours} ساعة';
    if (diff.inMinutes > 0) return 'منذ ${diff.inMinutes} دقيقة';
    return 'الآن';
  }

  /// Converts to a Firestore-compatible map.
  /// Stores [markedAt] as a Firestore [Timestamp], not an ISO string.
  Map<String, dynamic> toMap() => {
        'id': id,
        'pageNumber': pageNumber,
        'surahNumber': surahNumber,
        'ayahNumber': ayahNumber,
        'type': type.name,
        'xPosition': xPosition,
        'yPosition': yPosition,
        'wordText': wordText,
        'correctionNote': correctionNote,
        'markedAt':
            markedAt != null ? Timestamp.fromDate(markedAt!) : null,
      };
}

// ─────────────────────────────────────────────────────────────────────────────
// MISTAKE TYPE LABEL EXTENSIONS
// Single source of truth — delete MistakeTypeExtensions from session_model.dart
// ─────────────────────────────────────────────────────────────────────────────

extension MistakeTypeExtensions on MistakeType {
  /// Short Arabic label used in chips / dropdowns.
  String get arabicLabel {
    switch (this) {
      case MistakeType.tajweed:       return 'تجويد';
      case MistakeType.pronunciation: return 'نطق';
      case MistakeType.reading:       return 'قراءة';
      case MistakeType.skip:          return 'تخطي';
      case MistakeType.addition:      return 'زيادة';
      case MistakeType.other:         return 'أخرى';
    }
  }

  /// Full descriptive label used in dialogs / tooltips.
  String get fullLabel {
    switch (this) {
      case MistakeType.tajweed:       return 'خطأ تجويد';
      case MistakeType.pronunciation: return 'خطأ نطق';
      case MistakeType.reading:       return 'قراءة خاطئة';
      case MistakeType.skip:          return 'تجاوز';
      case MistakeType.addition:      return 'زيادة';
      case MistakeType.other:         return 'أخرى';
    }
  }

  /// Descriptive sentence used in help text / accessibility labels.
  String get description {
    switch (this) {
      case MistakeType.tajweed:       return 'خطأ في أحكام التجويد';
      case MistakeType.pronunciation: return 'خطأ في النطق';
      case MistakeType.reading:       return 'خطأ في القراءة';
      case MistakeType.skip:          return 'تخطي كلمة أو آية';
      case MistakeType.addition:      return 'إضافة كلمة غير موجودة';
      case MistakeType.other:         return 'خطأ آخر';
    }
  }

  /// Icon name string (used for serialisation / lookup).
  String get iconName {
    switch (this) {
      case MistakeType.tajweed:       return 'auto_fix_high';
      case MistakeType.pronunciation: return 'record_voice_over';
      case MistakeType.reading:       return 'error_outline';
      case MistakeType.skip:          return 'fast_forward';
      case MistakeType.addition:      return 'add_circle_outline';
      case MistakeType.other:         return 'help_outline';
    }
  }
}
