// Generated by FlutterFire CLI — web platform only.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNrasj-zIY1IYnZ-XKmeaITRfsHe4xmA',
    appId: '1:945631030984:web:ffa37928cad01e87d37ffd',
    messagingSenderId: '945631030984',
    projectId: 'mohaffez-ba2ec',
    authDomain: 'mohaffez-ba2ec.firebaseapp.com',
    storageBucket: 'mohaffez-ba2ec.firebasestorage.app',
    measurementId: 'G-GFPGKX13SP',
  );
}
